"""File persistence tools — per-agent scratch directory for deliverable outputs.

Archival memory is for the agent to retrieve by meaning. File persistence
is for the human to retrieve by name. Agent-internal vs agent-external.

Three tools: file_write, file_read, file_list. They operate on a per-agent
directory on the server filesystem. Paths are always relative to the agent's
directory. No absolute paths, no path traversal, no null bytes.

The agent writes files. The human picks them up via the API.
"""

import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from letta.log import get_logger

logger = get_logger(__name__)

# Default limits — overridden by settings if available
_DEFAULT_MAX_FILE_SIZE = 1_000_000  # 1MB
_DEFAULT_MAX_TOTAL_SIZE = 50_000_000  # 50MB


def _get_limits():
    """Read size limits from file_persistence_settings, falling back to defaults."""
    try:
        from letta.settings import file_persistence_settings

        max_file = file_persistence_settings.max_file_size_bytes
        max_total = file_persistence_settings.max_total_size_bytes
    except Exception:
        max_file = _DEFAULT_MAX_FILE_SIZE
        max_total = _DEFAULT_MAX_TOTAL_SIZE
    return max_file, max_total


def _agent_file_dir(agent_state) -> Path:
    """Return the per-agent file directory, creating it if needed."""
    # Inside sandboxed tool execution the sandbox sets LETTA_AGENT_FILES_DIR
    # to the exact server-computed path (the child may compute a different
    # ~/.letta under a different env). Prefer it when present.
    env_dir = os.environ.get("LETTA_AGENT_FILES_DIR")
    if env_dir:
        agent_dir = Path(env_dir)
        # Directory is created (and Landlock-read-granted) by the sandbox
        # spawn side; do not attempt mkdir here (write-denied in-sandbox).
        return agent_dir
    try:
        from letta.settings import file_persistence_settings, settings

        base = Path(file_persistence_settings.agent_files_dir or os.path.join(str(settings.letta_dir), "agent_files"))
    except Exception:
        base = Path(os.path.expanduser("~/.letta/agent_files"))
    agent_dir = base / agent_state.id
    agent_dir.mkdir(parents=True, exist_ok=True)
    return agent_dir


def _write_base_dir(agent_state) -> Path:
    """Return the base directory WRITES should target.

    Under the Landlock sandbox, only <agent_dir>/.staging is write-granted;
    the sandbox executor promotes staged files into the agent dir (with
    size/path validation) after each tool call. Outside the sandbox,
    writes go directly to the agent dir.
    """
    staging = os.environ.get("LETTA_STAGING_DIR")
    if staging:
        return Path(staging)
    return _agent_file_dir(agent_state)


def _validate_path(base_dir: Path, path: str) -> Path:
    """Validate and resolve a path relative to the agent's file directory.

    Rejects path traversal attempts (..), absolute paths, and null bytes.
    Returns the resolved absolute path.
    Raises ValueError if the path escapes the agent directory.
    """
    if not path:
        raise ValueError("Path cannot be empty")
    if "\0" in path:
        raise ValueError("Path contains null bytes")
    if path.startswith("/"):
        raise ValueError("Absolute paths are not allowed")
    if ".." in Path(path).parts:
        raise ValueError("Path traversal (..) is not allowed")

    resolved = (base_dir / path).resolve()
    base_resolved = base_dir.resolve()
    if not str(resolved).startswith(str(base_resolved) + os.sep) and resolved != base_resolved:
        raise ValueError(f"Path escapes agent file directory: {path}")
    return resolved


def file_write(agent_state, path: str, content: str) -> str:
    """Write content to a file in the agent's workspace.

    The file is stored in the agent's per-agent directory on the server.
    If the file already exists, it is overwritten. The path must be
    relative (no leading /) and cannot contain .. or null bytes.

    Use this when you want to:
    - Save a report, CSV, JSON, or markdown file for the human to retrieve
    - Write source code or configuration generated by the agent
    - Store structured data that doesn't fit in archival memory

    Args:
        path: Relative file path (e.g., "reports/summary.md", "data/output.csv")
        content: The text content to write to the file

    Returns:
        str: Confirmation message with the file path and size
    """
    base_dir = _write_base_dir(agent_state)
    file_path = _validate_path(base_dir, path)

    max_file_size, max_total_size = _get_limits()

    # Per-file size check
    content_bytes = content.encode("utf-8")
    if len(content_bytes) > max_file_size:
        raise ValueError(
            f"File content exceeds per-file limit "
            f"({len(content_bytes)} > {max_file_size} bytes). "
            f"Write a smaller file or split the content."
        )

    # Per-agent total size check (accounting against the persistent agent
    # dir — staged writes get re-validated during promotion)
    persistent_dir = _agent_file_dir(agent_state)
    total_size = 0
    if persistent_dir.exists():
        for f in persistent_dir.rglob("*"):
            if f.is_file() and ".staging" not in f.parts:
                total_size += f.stat().st_size

    # If overwriting an existing file, subtract its current size
    if file_path.exists() and file_path.is_file():
        total_size -= file_path.stat().st_size

    if total_size + len(content_bytes) > max_total_size:
        raise ValueError(
            f"Total storage would exceed per-agent limit "
            f"({total_size + len(content_bytes)} > {max_total_size} bytes). "
            f"Delete existing files to make room."
        )

    # Create parent directories
    file_path.parent.mkdir(parents=True, exist_ok=True)

    # Write the file
    file_path.write_text(content, encoding="utf-8")
    try:
        file_path.chmod(0o644)
    except OSError:
        pass  # chmod can fail on some platforms (Windows)

    return f"Wrote {len(content_bytes)} bytes to {path}"


def file_read(agent_state, path: str) -> str:
    """Read content from a file in the agent's workspace.

    Args:
        path: Relative file path to read

    Returns:
        str: The file content, or an error message if the file doesn't exist
    """
    base_dir = _agent_file_dir(agent_state)
    file_path = _validate_path(base_dir, path)

    if not file_path.exists():
        return f"File not found: {path}"
    if not file_path.is_file():
        return f"Not a file: {path}"

    return file_path.read_text(encoding="utf-8")


def file_list(agent_state, prefix: Optional[str] = None) -> str:
    """List files in the agent's workspace.

    Returns JSON with name, size, and modified_at for each file.
    Machine-readable for the API endpoint, parseable by the LLM.

    Args:
        prefix: Optional path prefix to filter results (e.g., "reports/")

    Returns:
        str: JSON list of file objects with name, size, and modified_at
    """
    base_dir = _agent_file_dir(agent_state)

    if prefix:
        search_dir = _validate_path(base_dir, prefix)
    else:
        search_dir = base_dir

    if not search_dir.exists():
        return json.dumps([])

    files = sorted(f for f in search_dir.rglob("*") if f.is_file())

    result = []
    for f in files:
        rel = str(f.relative_to(base_dir))
        stat = f.stat()
        result.append(
            {
                "name": rel,
                "size": stat.st_size,
                "modified_at": datetime.fromtimestamp(stat.st_mtime, tz=timezone.utc).isoformat(),
            }
        )

    return json.dumps(result)
